export type VSCode = typeof vscode;
export type SuccessFalse = typeof successFalse;
export type SuccessTrue = typeof successTrue;
export type TypeError = typeof typeError;
export type TypeWarning = typeof typeWarning;
export type ErrorNotStandardized = typeof errorNotStandardized;
export type ERROR_NOT_STANDARDIZED_TYPE = typeof ERROR_NOT_STANDARDIZED;
export type MakeSuccessFalseTypeError = typeof makeSuccessFalseTypeError;
export type MakeSuccessFalseTypeWarning = typeof makeSuccessFalseTypeWarning;
export type ShowVSCodeError = typeof showVSCodeError;
export type ErrorTypeError<T extends string, U extends string> = ReturnType<typeof makeSuccessFalseTypeError<T, U>>["errors"][0];
export type ErrorTypeWarning<T extends string, U extends string> = ReturnType<typeof makeSuccessFalseTypeWarning<T, U>>["errors"][0];
export type EscapeRegex = typeof escapeRegex;
import * as vscode from "vscode";
import { successFalse } from "../../source/library/index.js";
import { successTrue } from "../../source/library/index.js";
import { typeError } from "../../source/library/index.js";
import { typeWarning } from "../../source/library/index.js";
import { errorNotStandardized } from "../../source/library/index.js";
import { ERROR_NOT_STANDARDIZED } from "../../source/library/index.js";
import { makeSuccessFalseTypeError } from "../../source/library/index.js";
import { makeSuccessFalseTypeWarning } from "../../source/library/index.js";
import { showVSCodeError } from "../../source/library/index.js";
import { escapeRegex } from "../../source/library/index.js";
