export const runtimeVariables = /** @type {const} */ ([
  // errorMessages
  [
    "EN#COMPOSEDVARIABLESEXCLUSIVES#RUNTIMEVARIABLES#ERRORS#MESSAGES#ERRORNOTSTANDARDIZED",
    ["ERROR_NOT_STANDARDIZED_MESSAGE", "errorMessages", "errorNotStandardized"],
  ], // [key, [item, group, property]]
  // errorStatuses
  [
    "EN#COMPOSEDVARIABLESEXCLUSIVES#RUNTIMEVARIABLES#ERRORS#STATUSES#ERRORNOTSTANDARDIZED",
    ["ERROR_NOT_STANDARDIZED_STATUS", "errorStatuses", "errorNotStandardized"],
  ],
  // errorTypes
  [
    "EN#COMPOSEDVARIABLESEXCLUSIVES#RUNTIMEVARIABLES#ERRORS#TYPES#ERROR",
    ["ERROR", "errorTypes", "error"],
  ],
  [
    "EN#COMPOSEDVARIABLESEXCLUSIVES#RUNTIMEVARIABLES#ERRORS#TYPES#WARNING",
    ["WARNING", "errorTypes", "warning"],
  ],
  // defaults
  [
    "EN#COMPOSEDVARIABLESEXCLUSIVES#RUNTIMEVARIABLES#DEFAULTS#NUMBEROFERRORS",
    ["DEFAULT_NUMBER_OF_ERRORS", "defaults", "numberOfErrors"],
  ],
  // miscellaneous
  [
    "EN#COMPOSEDVARIABLESEXCLUSIVES#RUNTIMEVARIABLES#MISCELLANEOUS#ELLIPSIS",
    ["ELLIPSIS", "miscellaneous", "ellipsis"],
  ],
  [
    "EN#COMPOSEDVARIABLESEXCLUSIVES#RUNTIMEVARIABLES#MISCELLANEOUS#TRUE",
    ["TRUE", "miscellaneous", "true"],
  ],
  [
    "EN#COMPOSEDVARIABLESEXCLUSIVES#RUNTIMEVARIABLES#MISCELLANEOUS#FALSE",
    ["FALSE", "miscellaneous", "false"],
  ],
  // stringIdentifiers
  [
    "EN#COMPOSEDVARIABLESEXCLUSIVES#RUNTIMEVARIABLES#IDENTIFIERS#STRINGS#ERRORNOTSTANDARDIZEDMESSAGE",
    [
      "ERROR_NOT_STANDARDIZED_MESSAGE_IDENTIFIER",
      "stringIdentifiers",
      "errorNotStandardizedMessage",
    ],
  ],
  [
    "EN#COMPOSEDVARIABLESEXCLUSIVES#RUNTIMEVARIABLES#IDENTIFIERS#STRINGS#ERRORNOTSTANDARDIZEDSTATUS",
    [
      "ERROR_NOT_STANDARDIZED_STATUS_IDENTIFIER",
      "stringIdentifiers",
      "errorNotStandardizedStatus",
    ],
  ],
  [
    "EN#COMPOSEDVARIABLESEXCLUSIVES#RUNTIMEVARIABLES#IDENTIFIERS#STRINGS#ELLIPSIS",
    ["ELLIPSIS_IDENTIFIER", "stringIdentifiers", "ellipsis"],
  ],
  // objectIdentifiers
  [
    "EN#COMPOSEDVARIABLESEXCLUSIVES#RUNTIMEVARIABLES#IDENTIFIERS#OBJECTS#SUCCESSFALSE",
    ["SUCCESS_FALSE_IDENTIFIER", "objectIdentifiers", "successFalse"],
  ],
  [
    "EN#COMPOSEDVARIABLESEXCLUSIVES#RUNTIMEVARIABLES#IDENTIFIERS#OBJECTS#SUCCESSTRUE",
    ["SUCCESS_TRUE_IDENTIFIER", "objectIdentifiers", "successTrue"],
  ],
  [
    "EN#COMPOSEDVARIABLESEXCLUSIVES#RUNTIMEVARIABLES#IDENTIFIERS#OBJECTS#TYPEERROR",
    ["TYPE_ERROR_IDENTIFIER", "objectIdentifiers", "typeError"],
  ],
  [
    "EN#COMPOSEDVARIABLESEXCLUSIVES#RUNTIMEVARIABLES#IDENTIFIERS#OBJECTS#TYPEWARNING",
    ["TYPE_WARNING_IDENTIFIER", "objectIdentifiers", "typeWarning"],
  ],
  // functionIdentifiers
  [
    "EN#COMPOSEDVARIABLESEXCLUSIVES#RUNTIMEVARIABLES#IDENTIFIERS#FUNCTIONS#MAKESUCCESSFALSETYPEERROR",
    [
      "MAKE_SUCCESS_FALSE_TYPE_ERROR_IDENTIFIER",
      "functionIdentifiers",
      "makeSuccessFalseTypeError",
    ],
  ],
  [
    "EN#COMPOSEDVARIABLESEXCLUSIVES#RUNTIMEVARIABLES#IDENTIFIERS#FUNCTIONS#MAKESUCCESSFALSETYPEWARNING",
    [
      "MAKE_SUCCESS_FALSE_TYPE_WARNING_IDENTIFIER",
      "functionIdentifiers",
      "makeSuccessFalseTypeWarning",
    ],
  ],
  [
    "EN#COMPOSEDVARIABLESEXCLUSIVES#RUNTIMEVARIABLES#IDENTIFIERS#FUNCTIONS#MAKEERRORTYPEERROR",
    [
      "MAKE_ERROR_TYPE_ERROR_IDENTIFIER",
      "functionIdentifiers",
      "makeErrorTypeError",
    ],
  ],
  [
    "EN#COMPOSEDVARIABLESEXCLUSIVES#RUNTIMEVARIABLES#IDENTIFIERS#FUNCTIONS#MAKEERRORTYPEWARNING",
    [
      "MAKE_ERROR_TYPE_WARNING_IDENTIFIER",
      "functionIdentifiers",
      "makeErrorTypeWarning",
    ],
  ],
  [
    "EN#COMPOSEDVARIABLESEXCLUSIVES#RUNTIMEVARIABLES#IDENTIFIERS#FUNCTIONS#SHOWVSCODEERROR",
    ["SHOW_VS_CODE_ERROR_IDENTIFIER", "functionIdentifiers", "showVSCodeError"],
  ],
  [
    "EN#COMPOSEDVARIABLESEXCLUSIVES#RUNTIMEVARIABLES#IDENTIFIERS#FUNCTIONS#TREATVSCODEERRORS",
    [
      "TREAT_VS_CODE_ERRORS_IDENTIFIER",
      "functionIdentifiers",
      "treatVSCodeErrors",
    ],
  ],
  [
    "EN#COMPOSEDVARIABLESEXCLUSIVES#RUNTIMEVARIABLES#IDENTIFIERS#FUNCTIONS#LOGCLIERROR",
    ["LOG_CLI_ERROR_IDENTIFIER", "functionIdentifiers", "logCLIError"],
  ],
  [
    "EN#COMPOSEDVARIABLESEXCLUSIVES#RUNTIMEVARIABLES#IDENTIFIERS#FUNCTIONS#ESCAPEREGEX",
    ["ESCAPE_REGEX_IDENTIFIER", "functionIdentifiers", "escapeRegex"],
  ],
  [
    "EN#COMPOSEDVARIABLESEXCLUSIVES#RUNTIMEVARIABLES#IDENTIFIERS#FUNCTIONS#TRIMSTRINGWITHLIMIT",
    [
      "TRIM_STRING_WITH_LIMIT_IDENTIFIER",
      "functionIdentifiers",
      "trimStringWithLimit",
    ],
  ],
  [
    "EN#COMPOSEDVARIABLESEXCLUSIVES#RUNTIMEVARIABLES#IDENTIFIERS#FUNCTIONS#SPACEOUTESLINTMESSAGE",
    [
      "SPACE_OUT_ESLINT_MESSAGE_IDENTIFIER",
      "functionIdentifiers",
      "spaceOutESLintMessage",
    ],
  ],
  [
    "EN#COMPOSEDVARIABLESEXCLUSIVES#RUNTIMEVARIABLES#IDENTIFIERS#FUNCTIONS#HIGHLIGHTFIRSTLINEOFCODE",
    [
      "HIGHLIGHT_FIRST_LINE_OF_CODE_IDENTIFIER",
      "functionIdentifiers",
      "highlightFirstLineOfCode",
    ],
  ],
  [
    "EN#COMPOSEDVARIABLESEXCLUSIVES#RUNTIMEVARIABLES#IDENTIFIERS#FUNCTIONS#PATHEXISTSASAFILE",
    [
      "PATH_EXISTS_AS_A_FILE_IDENTIFIER",
      "functionIdentifiers",
      "pathExistsAsAFile",
    ],
  ],
  [
    "EN#COMPOSEDVARIABLESEXCLUSIVES#RUNTIMEVARIABLES#IDENTIFIERS#FUNCTIONS#PATHEXISTSASADIRECTORY",
    [
      "PATH_EXISTS_AS_A_DIRECTORY_IDENTIFIER",
      "functionIdentifiers",
      "pathExistsAsADirectory",
    ],
  ],
  // argumentIdentifiers
  [
    "EN#COMPOSEDVARIABLESEXCLUSIVES#RUNTIMEVARIABLES#IDENTIFIERS#ARGUMENTS#MESSAGE",
    ["MESSAGE_IDENTIFIER", "argumentIdentifiers", "message"],
  ],
  [
    "EN#COMPOSEDVARIABLESEXCLUSIVES#RUNTIMEVARIABLES#IDENTIFIERS#ARGUMENTS#STATUS",
    ["STATUS_IDENTIFIER", "argumentIdentifiers", "status"],
  ],
  // propertyIdentifiers
  [
    "EN#COMPOSEDVARIABLESEXCLUSIVES#RUNTIMEVARIABLES#IDENTIFIERS#PROPERTIES#SUCCESS",
    ["SUCCESS_IDENTIFIER", "propertyIdentifiers", "success"],
  ],
  [
    "EN#COMPOSEDVARIABLESEXCLUSIVES#RUNTIMEVARIABLES#IDENTIFIERS#PROPERTIES#TYPE",
    ["TYPE_IDENTIFIER", "propertyIdentifiers", "type"],
  ],
  [
    "EN#COMPOSEDVARIABLESEXCLUSIVES#RUNTIMEVARIABLES#IDENTIFIERS#PROPERTIES#ERRORS",
    ["ERRORS_IDENTIFIER", "propertyIdentifiers", "errors"],
  ],
]);
